<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import numpy as np

In [136]:
x = np.array([5,4,9,10])
x.ndim

1

In [137]:
x = np.array([[5,4],[9,10]], dtype = np.int32)
y = np.array([[1,2],[74,4]], dtype= np.float64)

x.ndim

2

In [138]:
x.itemsize

4

In [139]:
x

array([[ 5,  4],
       [ 9, 10]], dtype=int32)

In [140]:
x[1,0] = 4

In [141]:
x

array([[ 5,  4],
       [ 4, 10]], dtype=int32)

In [142]:
x.dtype

dtype('int32')

In [143]:
y.dtype

dtype('float64')

In [144]:
z = (x+y)

In [145]:
x.nbytes

16

In [146]:
y.nbytes

32

In [147]:
z.nbytes

32

In [148]:
z.shape

(2, 2)

In [149]:
np.sort(z)

array([[ 6.,  6.],
       [14., 78.]])

In [150]:
np.sort(z, axis =None) # flatten array

array([ 6.,  6., 14., 78.])

In [151]:
z

array([[ 6.,  6.],
       [78., 14.]])

In [152]:
z.flatten() # New array with flatten()

array([ 6.,  6., 78., 14.])

In [153]:
z # original array is not flat

array([[ 6.,  6.],
       [78., 14.]])

In [154]:
z.ravel() # a flat view of array z

array([ 6.,  6., 78., 14.])

In [155]:
z

array([[ 6.,  6.],
       [78., 14.]])

In [156]:
z.reshape(4,1)

array([[ 6.],
       [ 6.],
       [78.],
       [14.]])

In [157]:
z

array([[ 6.,  6.],
       [78., 14.]])

In [158]:
z.min()

np.float64(6.0)

In [159]:
z.max()

np.float64(78.0)

In [165]:
z.sum(axis=1) # a1+a2 , b1+b2(co-ordinal values)

array([12., 92.])

In [167]:
z.sum(axis=0) # a1+b1 , a2+b2 (co-ordinal values)

array([84., 20.])

In [168]:
z

array([[ 6.,  6.],
       [78., 14.]])

In [169]:
for row in z:
  print("row :-> ",row)

row :->  [6. 6.]
row :->  [78. 14.]


In [170]:
np.sqrt(z)

array([[2.44948974, 2.44948974],
       [8.83176087, 3.74165739]])

In [172]:
np.mean(z)

np.float64(26.0)

In [171]:
np.std(z) #standard deviation

np.float64(30.199337741083)