<a href="https://colab.research.google.com/github/devmofizur/Python/blob/main/Numpy/More_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
a = np.array([[4,5,6],[9,11,-4]])

In [5]:
a

array([[ 4,  5,  6],
       [ 9, 11, -4]])

In [10]:
a[:,2] # index 2 from all columns

array([ 6, -4])

In [11]:
a[:1,:2] # inclusive:exclusive -> print row 0 column 0 and 1

array([[4, 5]])

In [12]:
a[:,:2] # inclusive:exclusive -> print row 0,1 column 0,1

array([[ 4,  5],
       [ 9, 11]])

In [15]:
# Customer ID, Name
customers = np.array([
    [1, 'Alice'],
    [2, 'Bob'],
    [3, 'Charlie']
])
# Customer ID, purchase amount , purchase date
purchases = np.array([
    [1, 250.0, '2026-04-01'],
    [2, 300.5, '2026-04-02'],
    [1, 120.0, '2026-04-03']
])

In [27]:
horizontal_stack = np.hstack((customers,purchases)) # combining two numpy array horizontally. yes it is blind and repeats id
horizontal_stack

array([['1', 'Alice', '1', '250.0', '2026-04-01'],
       ['2', 'Bob', '2', '300.5', '2026-04-02'],
       ['3', 'Charlie', '1', '120.0', '2026-04-03']], dtype='<U32')

In [29]:
np.hsplit(horizontal_stack,[2])

[array([['1', 'Alice'],
        ['2', 'Bob'],
        ['3', 'Charlie']], dtype='<U32'),
 array([['1', '250.0', '2026-04-01'],
        ['2', '300.5', '2026-04-02'],
        ['1', '120.0', '2026-04-03']], dtype='<U32')]

In [30]:
purchases[:,1:3]

array([['250.0', '2026-04-01'],
       ['300.5', '2026-04-02'],
       ['120.0', '2026-04-03']], dtype='<U32')

In [31]:
vertical_stack = np.vstack((customers,purchases[:,1:3])) # combining two numpy array vertically. yes it is blind and repeats id
vertical_stack

array([['1', 'Alice'],
       ['2', 'Bob'],
       ['3', 'Charlie'],
       ['250.0', '2026-04-01'],
       ['300.5', '2026-04-02'],
       ['120.0', '2026-04-03']], dtype='<U32')

In [34]:
np.hsplit(vertical_stack,[1])

[array([['1'],
        ['2'],
        ['3'],
        ['250.0'],
        ['300.5'],
        ['120.0']], dtype='<U32'),
 array([['Alice'],
        ['Bob'],
        ['Charlie'],
        ['2026-04-01'],
        ['2026-04-02'],
        ['2026-04-03']], dtype='<U32')]

In [50]:
np.max(horizontal_stack[:,3].astype(np.float64)) # max value from purchase amount converted data type unicode to float64

np.float64(300.5)

In [ ]:
np.argmax(horizontal_stack[:,3].astype(np.float64)) # max value index from purchase amount converted data type unicode to float64

In [35]:
sales = np.array([12, 47, 50, 3, 88, 65, 29, 50, 91, 44])
profit = sales >40
profit

array([False,  True,  True, False,  True,  True, False,  True,  True,
        True])

In [36]:
sales[profit]

array([47, 50, 88, 65, 50, 91, 44])

In [37]:
sales.max()

np.int64(91)

In [51]:
np.argmax(sales) # max value index number

np.int64(8)